### PR TITLE
Menu vs modal

### PR DESCRIPTION
**Pull request by zorkow**
This should fix the focus problems. The idea is to
--  to move the menu into the modal
-- reposition it correctly
-- catch focus events 

Also fixes problem that the menu might be left over when modal is quite via Escape key.

### CODE REVIEW

**Comment by pkra** [comment]
Quick test results.
- works fine on Chrome, IE9, IE11
- FF needs an extra tab to enter the menu after opening it
- Edge needs three extra tabs to enter the menu after opening it.

I think that's sufficient.

**Comment by zorkow** [comment]
- works also fine on Safari, Opera, Konqueror
- Edge: the problem is that the focus is reset to the modal's base element, meaning that one has to tap over the close button and the renderer box again. Maybe attaching a tab index might help.

**Comment by zorkow** [comment]
PS: Failed checks. Are all these broken links normal?

**Comment by pkra** [comment]
> PS: Failed checks. Are all these broken links normal?

I'm afraid so. I haven't got around fixing all of them yet and the tool we use is over eager (e.g., can't follow redirects).

**Comment by pkra** [comment]
And you just scared me ;-) your branch is behind and a couple of links in the 2.6-beta announcement have been fixed

**Comment by zorkow** [comment]
The problem with Edge and FF was that the focus fired before the element was attached. Focus now optionally refires after 100ms, that seems to solve the problem.

**Comment by pkra** [comment]
Alright. This is good enough for now.

**Pull request merged**
