### PR TITLE
Update MathJax version in snippet on home page

### PR DESCRIPTION
**Pull request by andportnoy**

### CODE REVIEW

**Comment by dpvc** [comment]
Actually, I'd like to see it call `latest.js` rather than `MathJax.js` so that the link doesn't have to be changed in the future.

**Comment by andportnoy** [comment]
@dpvc So, `cdn.mathjax.org/mathjax/latest/MathJax.js`?

Edit:
Sorry, closed request accidentally.

**Comment by dpvc** [comment]
no, `cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/latest.js`, which will end up loading from whatever version is actually the latest one on cdnjs, regardless of the 2.7.1 in the URL.

**Comment by andportnoy** [comment]
@dpvc Sorry for the misunderstanding!

**Comment by pkra** [comment]
>  Actually, I'd like to see it call latest.js rather than MathJax.js so that the link doesn't have to be changed in the future.

I disagree on that one. I think it should link to proper copy of MathJax to avoid confusion. 

I think we can use https://help.github.com/articles/repository-metadata-on-github-pages/ to update the version automatically. But even if not, updating the snippet is easy enough and a simple addition to our release process.

The main reason it didn't occur [EDIT: to me earlier] was the unusual process of the 2.7.1 release.

**Comment by pkra** [comment]
Admittedly, a secondary reason not to change it is the json problem on cdnjs. So I'd prefer to wait with changes until 2.7.2. anyway.

**Comment by pkra** [comment]
For some reason, I can't get the metadata plugin's `github.site.latest_release` to give me something non-empty. 

Still, using the first item from the release might be ok (even if though it includes beta releases).

**Comment by pkra** [comment]
Note: this requires some changes to the _config.yaml

**Comment by dpvc** [comment]
> updating the snippet is easy enough and a simple addition to our release process.

It is easy for us to change this page, but because this is a snippet to be copied and used by page authors, it is *not* easy to change that once it has been copied.  We know that authors will only go back and change their pages if something breaks, so if this snippet is used, pages will become fixed at whatever version of MathJax they had when they were written, and whatever bugs that entails.  That is why I think `latest.js` is better than `MathJax.js` as the recommended link.

We can, of course, update the 2.7.x as new versions come out, if you want (I don't have any problem with that), but my main intention is to get `latest.js` to be used rather than `MathJax.js`.  Up until the change in CDN, we had always recommended the `mathjax/latest` URL, and for most people who would be copying from this link, I think that is the right thing to use.

**Comment by pkra** [comment]
> That is why I think latest.js is better than MathJax.js as the recommended link.

I understand but disagree. Using `latest` versions of third-party dependencies is an anti-pattern that should not be encouraged.

**Comment by dpvc** [comment]
> Using latest versions of third-party dependencies is an anti-pattern that should not be encouraged.

I understand but disagree in this case.  For people putting together sites where their code interacts with MathJax ins some way, then yes, I would agree that keeping a particular version might be the right way to go.  But those people are already going to have to be dealing with MathJax in a more sophisticated way, and will be having to keep versions of all their software in mind.  I don't think that is the audience for this code snippet.  This is for people who want to plop MathJax into their website and forget about it.  Using `latest` is the right thing for them.  We know from experience that those users are never going to update the link to new versions as they come out.  So the version-specific snippet is going to lead to websites that break over time as browsers change and they fail to get the updates from future versions of MathJax.  The Safari vector problem is a case in point.  Users who have used the 2.7.1 link are never going to get that update unless they go back and change all the pages that use that link.  And they may never even know there is a problem unless someone viewing their site with Safari complains (if they aren't Safari users themselves).

**Comment by pkra** [comment]
>  This is for people who want to plop MathJax into their website and forget about it. 

Besides the fact that this behavior is not actually healthy for the project (as such users forget what kind of work goes into MathJax), I've seen way too many professional publishers loading MathJax with the good old `TeX-AMS-MML_HTMLorMML` configuration. Even among sponsors, even when I tell them it's not efficient for them. This indicates that devs just grab what's there (or in the "getting started" section in the docs) and never think twice about it.  And even the most supportive teams can jump to false conclusions (remember that screwed up StackOverflow discussion about loading MathJax that comes up in every other discussion about performance?). This is a huge problem for the project.

Also, pointing to `cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/latest.js` is more problematic than pointing at some `latest/MathJax.js` link (which e.g., jsdelivr could provide) because a) it's not even linking to MathJax and b) the fact that v2.7.1 is part of the link will invariably lead to confusion.

> We know from experience that those users are never going to update the link to new versions as they come out.

We can't really know that since we have been encouraging them not to update by providing `cdn.mathjax.org/mathjax/latest/`. 

Equally likely a large population of "link and forget" users are using third party software to integrate MathJax (e.g., a CMS plugin). The maintainers of those plugins will quite likely update their plugins on every MathJax release, eliminating the problem.

> So the version-specific snippet is going to lead to websites that break over time as browsers change and they fail to get the updates from future versions of MathJax. 

Which is the expected behavior if a site is not maintained.

---

To be clear, I'm not saying people shouldn't use a trick like `latest.js` nor that we should not document it (which, sadly, we haven't). 

I'm saying we should not encourage this as the default by posting it to the front page of www.mathjax.org (or the "getting started" section). It causes way more problems than it solves.

**Comment by dpvc** [comment]
I have included an update to the snippet in a recent update to the website.  Thanks for your contribution; we appreciate it!

**Pull request closed without merging**
