### PR TITLE
fix scaling demo

### LINKED ISSUE #49: Scaling demo sets wrong amount of space
The rescaling accessibility demo is broken in several ways.  
- As reported [here](https://groups.google.com/d/msg/mathjax-dev/WG4OacQc3D0/_Cz25hq9AQAJ),  the space for the demo isn't correct.  This seems to affect all output modes.
- The fast preview should be turned off (it make the scaled math flicker)
- Scaling should block until the previous typesetting is complete (so you don't get a whole slew of retype sets after you stop moving the slider).

### PR DESCRIPTION
**Pull request by pkra**
- disable fast-preview
- add timeout for scaling effect
- address @dpvc's suggestions
- fixes #49

### CODE REVIEW

**Comment by pkra** [comment]
@dpvc does that look ok to you?

**Comment by pkra** [comment]
_bump_ @dpvc @zorkow

**Comment by dpvc** [comment]
> does this look ok to you?

The anti-flikering code should not be needed if you set the `processSectionDelay` to 0.  That simplifies things a bit.

I don't think the timeout approach is the best one for this, as it makes the dragging rather choppy.  I would recommend an approach that actually keeps track of whether MathJax is running or not and doesn't issue more typeset calls until after it is done, even if the slider changes.  This is what I meant by throttling the typeset calls.  Here is some code that implements that idea.  I would recommend replacing [lines 146 to 176](https://github.com/mathjax/MathJax-website/blob/issue49/js/frontpage.js#L146-L176) with this.

```
/*
 *  For sizing-by-slider demo
 */
MathJax.Hub.processSectionDelay = 0;

MathJax.Hub.Register.StartupHook("onLoad", function () {
  var running = true;    //  MathJax is typesetting (true for initial typeset)
  var pending = false;   //  A size change has occurring while running
  var math;              //  The jax to be modified (filled in later)

  //
  //  Look up the elements we need
  //
  var STYLE = document.getElementById('output').style;
  var TEX = document.getElementById('tex');
  var SIZE = document.getElementById('size');

  //
  //  Look up the math element after it has been typeset
  //  And see if there has been a size change during the
  //    initial typesetting pass (unlikely);
  //
  MathJax.Hub.Queue(function () {
    math = MathJax.Hub.getAllJax('output')[0];
    checkPending();
  });

  //
  //  Set the font size for the output container
  //
  var setSize = function () {STYLE.fontSize = (parseFloat(SIZE.value)/5) + "em"};
  //
  //  Check if a size change is pending:
  //    If so, display the math at the new size
  //    Otherwise, indicate that Mathjax is no longer running
  //
  var checkPending = function () {if (pending) display(); else running = false};
  //
  //  Mark that we are typesetting, and no size change is pending
  //  Queue the size change, rerender the math at that size, and
  //    check if a size change occurred during the rendering.
  //
  var display = function () {
    running = true; pending = false;
    MathJax.Hub.Queue(setSize,["Rerender",math],checkPending);
  };

  //
  //  When the TeX changes, queue a change to the jax content.
  //  When the slider changes:
  //    If typesetting is already underway,
  //      indicate the pending size change,
  //      otherwise update the math to the new size
  //
  TEX.onchange = function () {MathJax.Hub.Queue(["Text",math,TEX.value])};
  SIZE.oninput = function () {if (running) pending = true; else display()};

  //
  //  Make sure the initial size corresponds to the
  //    initial slider position.
  //  
  setSize();
});
```

**Comment by pkra** [comment]
> The anti-flikering code should not be needed if you set the `processSectionDelay` to 0.  That simplifies things a bit.

That's not been my experience.

> I don't think the timeout approach is the best one for this, as it makes the dragging rather choppy.

I don't know what is chopping. Or I didn't see it on any of my browser tests. Not sure.

>  Here is some code that implements that idea. 

Thanks,

Since the code seems to be in working condition as is, I'll merge it so that the demo gets fixed. I'm happy to pull in your better solution. Could you turn your code into a PR instead?

**Comment by dpvc** [comment]
> That's not been my experience.

I've teting in Firefox, Chrome, Safari, and IE, and I don't get any jitter with `processSectionDelay = 0` and fast-preview off.  If extensions or fonts have to load, there will be a refresh for that, but once the code is cached, the scaling should be smooth.  What browser/OS combination causes problems for you?  Do you have cache disabled, perhaps?

> I don't know what is chopping. 

What I meant is that you don't get the math smoothly scaling as you drag the slider.  You have to stop and wait before it will resize.  I think if you compare that to the code I provided, you will see the difference I am talking about.

> Could you turn your code into a PR instead?

Done.  #53.

**Pull request merged**
